export function loadMapPage(){
    return `
    <main class="flex" style="height: calc(100vh - 80px);">
        <!-- Left panel -->
        <aside class="w-full md:w-1/3 border-r-2 border-gray-200 p-6 overflow-y-auto">
            <h1 class="text-2xl font-bold mb-4">Encuentra la mejor vet</h1>
            <div class="relative mb-4">
                <input id="searchInput" type="text" placeholder="Search by near or service"
                    class="w-full px-4 py-3 rounded-xl bg-blue-light/40 outline-none focus:ring-2 focus:ring-blue">
            </div>
            <div class="flex flex-wrap gap-2 mb-6 text-xs">
                <button class="px-3 py-1 rounded-full bg-pink text-white">All</button>
                <button class="px-3 py-1 rounded-full border">24h</button>
                <button class="px-3 py-1 rounded-full border">urgencias</button>
                <button class="px-3 py-1 rounded-full border">Poblado</button>
                <button class="px-3 py-1 rounded-full border">Laureles</button>
            </div>
            <!-- Cards generated by mapPage.js -->
            <div id="clinicList" class="space-y-4"></div>
        </aside>
        <!-- Right panel: map -->
        <div id="mapContainer" class="hidden md:block md:w-2/3"></div>
    </main>
    <!-- 1. logic after google maps -->
    <script src="../controllers/mapPage.js"></script>
    <!-- 2. Google Maps — invoca window.initMap definido en mapPage.js -->
    <script
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDoaEx8ykVQ4oyLJkP2yFzO2cmp8vT7Dk0&callback=initMap&libraries=places&v=weekly"
        async></script>`
}
export function mapPage(){
    
}