export const SERVICES_DATA = [
  // ── GROOMING & SPA ─────────────────────────────────────────────
  {
    cat: 'grooming',
    catLabel: 'Grooming & Spa',
    catIcon: '✂️',
    badgeBg: '#E0F2FE',
    badgeColor: '#0284C7',
    name: 'Bella & Fur Studio',
    avatar: 'https://i.pravatar.cc/80?img=47',
    location: 'El Poblado, Medellín',
    rating: '4.9',
    title: 'Premium Grooming & Spa Package',
    desc: 'Full grooming session including bath, haircut, nail trim and aromatherapy for your pet.',
    tags: ['Bath & Dry', 'Haircut', 'Nail Trim'],
    price: 'From $45,000',
    image: 'https://images.unsplash.com/photo-1520038410233-7141be7e6f97?w=560&q=80',
  },
  {
    cat: 'grooming',
    catLabel: 'Grooming & Spa',
    catIcon: '✂️',
    badgeBg: '#E0F2FE',
    badgeColor: '#0284C7',
    name: 'Paws & Polish',
    avatar: 'https://i.pravatar.cc/80?img=32',
    location: 'Laureles, Medellín',
    rating: '4.7',
    title: 'Spa Day for Dogs & Cats',
    desc: 'Relaxing spa treatments, coat conditioning and de-shedding therapy at your doorstep.',
    tags: ['Spa', 'De-shedding', 'Cats & Dogs'],
    price: 'From $38,000',
    image: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=560&q=80',
  },

  // ── PET SHOPS ──────────────────────────────────────────────────
  {
    cat: 'petshops',
    catLabel: 'Pet Shop',
    catIcon: '🛒',
    badgeBg: '#FEF9C3',
    badgeColor: '#B45309',
    name: 'MegaPet Medellín',
    avatar: 'https://i.pravatar.cc/80?img=12',
    location: 'Centro Comercial Oviedo',
    rating: '4.8',
    title: 'Complete Pet Store & Nutrition',
    desc: 'Premium food brands, accessories, toys and health products for all types of pets.',
    tags: ['Premium Food', 'Accessories', 'Toys'],
    price: 'Open now',
    image: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=560&q=80',
  },
  {
    cat: 'petshops',
    catLabel: 'Pet Shop',
    catIcon: '🛒',
    badgeBg: '#FEF9C3',
    badgeColor: '#B45309',
    name: 'Animal House Store',
    avatar: 'https://i.pravatar.cc/80?img=25',
    location: 'Envigado, Medellín',
    rating: '4.6',
    title: 'Natural & Organic Pet Products',
    desc: 'Specialist in organic food, natural supplements and eco-friendly pet accessories.',
    tags: ['Organic', 'Supplements', 'Eco-friendly'],
    price: 'Open now',
    image: 'https://images.unsplash.com/photo-1601758124510-52d02ddb7cbd?w=560&q=80',
  },

  // ── ADOPTION SHELTERS ──────────────────────────────────────────
  {
    cat: 'adoption',
    catLabel: 'Adoption',
    catIcon: '❤️',
    badgeBg: '#FCE7F3',
    badgeColor: '#9D174D',
    name: 'Huellitas Felices',
    avatar: 'https://i.pravatar.cc/80?img=44',
    location: 'Bello, Antioquia',
    rating: '5.0',
    title: 'Dog & Cat Adoption Center',
    desc: 'Over 80 pets ready for adoption. All vaccinated, dewormed and microchipped.',
    tags: ['Vaccinated', 'Microchipped', 'All ages'],
    price: 'Free adoption',
    image: 'https://images.unsplash.com/photo-1450778869180-41d0601e046e?w=560&q=80',
  },
  {
    cat: 'adoption',
    catLabel: 'Adoption',
    catIcon: '❤️',
    badgeBg: '#FCE7F3',
    badgeColor: '#9D174D',
    name: 'Refugio Patitas',
    avatar: 'https://i.pravatar.cc/80?img=55',
    location: 'Itagüí, Antioquia',
    rating: '4.9',
    title: 'Rescue & Adoption Shelter',
    desc: 'Non-profit shelter rescuing stray animals. Find your forever companion here.',
    tags: ['Non-profit', 'Rescue', 'Foster care'],
    price: 'Free adoption',
    image: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=560&q=80',
  },

  // ── DOG WALKERS ────────────────────────────────────────────────
  {
    cat: 'walkers',
    catLabel: 'Dog Walker',
    catIcon: '🦮',
    badgeBg: '#DCFCE7',
    badgeColor: '#15803D',
    name: 'Carlos Ríos',
    avatar: 'https://i.pravatar.cc/80?img=8',
    location: 'El Poblado, Medellín',
    rating: '4.9',
    title: 'Professional Dog Walker',
    desc: 'Certified dog trainer offering individual and group walks. GPS tracking included.',
    tags: ['GPS Tracking', 'Certified', 'Groups up to 4'],
    price: '$18,000 / walk',
    image: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=560&q=80',
  },
  {
    cat: 'walkers',
    catLabel: 'Dog Walker',
    catIcon: '🦮',
    badgeBg: '#DCFCE7',
    badgeColor: '#15803D',
    name: 'Sofía Martínez',
    avatar: 'https://i.pravatar.cc/80?img=23',
    location: 'Laureles, Medellín',
    rating: '4.8',
    title: 'Daily Dog Walks & Playtime',
    desc: 'Energetic and loving walks in Parque Laureles. Perfect for high-energy breeds.',
    tags: ['Daily walks', 'Playtime', 'Parque Laureles'],
    price: '$15,000 / walk',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=560&q=80',
  },

  // ── HOME VETERINARY ────────────────────────────────────────────
  {
    cat: 'homevet',
    catLabel: 'Home Vet',
    catIcon: '🩺',
    badgeBg: '#EDE9FE',
    badgeColor: '#7C3AED',
    name: 'Dr. Andrés Gómez',
    avatar: 'https://i.pravatar.cc/80?img=14',
    location: 'Medellín — covers all zones',
    rating: '4.9',
    title: 'Home Veterinary Consultations',
    desc: 'Licensed vet with 10+ years experience. Checkups, vaccines and lab tests at home.',
    tags: ['Vaccines', 'Lab tests', 'All species'],
    price: 'From $65,000',
    image: 'https://images.unsplash.com/photo-1559190394-df5a28aab5c5?w=560&q=80',
  },
  {
    cat: 'homevet',
    catLabel: 'Home Vet',
    catIcon: '🩺',
    badgeBg: '#EDE9FE',
    badgeColor: '#7C3AED',
    name: 'Dra. Valentina Hoyos',
    avatar: 'https://i.pravatar.cc/80?img=38',
    location: 'Envigado & El Poblado',
    rating: '5.0',
    title: 'Urgent & Preventive Home Care',
    desc: 'Emergency and preventive care at your door. Available weekends and holidays.',
    tags: ['Emergency', 'Weekends', 'Preventive care'],
    price: 'From $70,000',
    image: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=560&q=80',
  },

  // ── PASEADORES ─────────────────────────────────────────────────
  {
    cat: 'paseadores',
    catLabel: 'Paseadores',
    catIcon: '🐕',
    badgeBg: '#FEE2E4',
    badgeColor: '#E05A6A',
    name: 'Juliana Pérez',
    avatar: 'https://i.pravatar.cc/80?img=49',
    location: 'Envigado, Medellín',
    rating: '4.8',
    title: 'Paseos personalizados para perros',
    desc: 'Paseos individuales o en pareja con fotos del recorrido y reporte de actividad.',
    tags: ['Fotos incluidas', 'Reporte', 'Individual'],
    price: '$16,000 / paseo',
    image: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=560&q=80',
  },
  {
    cat: 'paseadores',
    catLabel: 'Paseadores',
    catIcon: '🐕',
    badgeBg: '#FEE2E4',
    badgeColor: '#E05A6A',
    name: 'Mateo Herrera',
    avatar: 'https://i.pravatar.cc/80?img=6',
    location: 'Sabaneta, Antioquia',
    rating: '4.7',
    title: 'Paseador certificado con experiencia',
    desc: 'Más de 3 años paseando perros de todas las razas. Rutas seguras y divertidas.',
    tags: ['Certificado', 'Todas las razas', 'Rutas seguras'],
    price: '$14,000 / paseo',
    image: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=560&q=80',
  },

  // ── GUARDERÍAS ─────────────────────────────────────────────────
  {
    cat: 'guarderias',
    catLabel: 'Guardería',
    catIcon: '🏠',
    badgeBg: '#FDF4FF',
    badgeColor: '#9333EA',
    name: 'Happy Paws Daycare',
    avatar: 'https://i.pravatar.cc/80?img=63',
    location: 'El Poblado, Medellín',
    rating: '4.9',
    title: 'Guardería diurna para perros',
    desc: 'Espacio amplio con jardín, juegos supervisados y cámaras en vivo para los dueños.',
    tags: ['Cámaras en vivo', 'Jardín', 'Juego supervisado'],
    price: '$35,000 / día',
    image: 'https://images.unsplash.com/photo-1601758124510-52d02ddb7cbd?w=560&q=80',
  },
  {
    cat: 'guarderias',
    catLabel: 'Guardería',
    catIcon: '🏠',
    badgeBg: '#FDF4FF',
    badgeColor: '#9333EA',
    name: 'Casa Canina Medellín',
    avatar: 'https://i.pravatar.cc/80?img=71',
    location: 'Laureles, Medellín',
    rating: '4.8',
    title: 'Hospedaje y guardería 24h',
    desc: 'Guardería con opción de hospedaje nocturno. Alimentación incluida y cuidado profesional.',
    tags: ['Hospedaje', 'Alimentación incluida', '24h'],
    price: '$55,000 / noche',
    image: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=560&q=80',
  },
];